// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part One: Understanding the Value of Chaos and Focus',
      link: {
        type: 'doc',
        id: 'part-one/index',
      },
      items: [
        'part-one/chapter1',
        'part-one/chapter2',
        'part-one/chapter3',
      ],
    },
    {
      type: 'category',
      label: 'Part Two: Building Your First Focus Room',
      link: {
        type: 'doc',
        id: 'part-two/index',
      },
      items: [
        'part-two/chapter4',
        'part-two/chapter5',
        'part-two/chapter6',
        'part-two/chapter7',
      ],
    },
    {
      type: 'category',
      label: 'Part Three: Expanding and Deepening',
      link: {
        type: 'doc',
        id: 'part-three/index',
      },
      items: [
        'part-three/chapter8',
        'part-three/chapter9',
        'part-three/chapter10',
        'part-three/chapter11',
        'part-three/chapter12',
      ],
    },
  ],
};

export default sidebars;
